name: Deploy to GKE


on: 
  push: 
    branches: ["main"]

jobs: 
  setup-build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set GCP Project
      run: gcloud config set project metal-hope-413718

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials cluster-1 --zone us-central1-c

    - name: Install Helm chart
      run: |
        helm install apache ./apache --set repository.image=kaizenacademy/python-app --set repository.tag=2.0.0





